Revert "DEBUG: csid_irq_storm debug change" on camera_lenovo
This reverts commit 6c9305c0b3993e3ba9e586fbcfc0c9483d5850fe

Reason:
../../../../../../kernel/lenovo/sm6150/drivers/media/platform/msm/camera_lenovo/cam_isp/isp_hw_mgr/hw_utils/irq_controller/cam_irq_controller.c:701:3: error: implicit declaration of function 'cam_io_w_vfe_mb' [-Werror,-Wimplicit-function-declaration]
                cam_io_w_vfe_mb(controller->irq_status_arr[i],
                ^
../../../../../../kernel/lenovo/sm6150/drivers/media/platform/msm/camera_lenovo/cam_isp/isp_hw_mgr/hw_utils/irq_controller/cam_irq_controller.c:701:3: note: did you mean 'cam_io_w_mb'?
../../../../../../kernel/lenovo/sm6150/drivers/media/platform/msm/camera/cam_utils/cam_io_util.h:43:5: note: 'cam_io_w_mb' declared here
int cam_io_w_mb(uint32_t data, void __iomem *addr);
    ^
../../../../../../kernel/lenovo/sm6150/drivers/media/platform/msm/camera_lenovo/cam_isp/isp_hw_mgr/hw_utils/irq_controller/cam_irq_controller.c:720:3: error: implicit declaration of function 'cam_io_w_vfe_mb' [-Werror,-Wimplicit-function-declaration]
                cam_io_w_vfe_mb(controller->global_clear_bitmask,
                ^
2 errors generated.

Change-Id: I9db7149a8c31d008307c283d143e8c47d60196c2